In [1]:
import numpy as  np

np.ones(5)

array([1., 1., 1., 1., 1.])

In [2]:
np.ones(
    (5,),
    dtype=int
)

array([1, 1, 1, 1, 1])

In [3]:
np.ones(
    (2,1)
)

array([[1.],
       [1.]])

In [4]:
s = (2,2)

np.ones(s)

array([[1., 1.],
       [1., 1.]])

In [5]:
# np.array

np.array(
    [1,2,3]
)

array([1, 2, 3])

In [6]:
np.array(
    [1, 2, 3.0]
)

array([1., 2., 3.])

In [7]:
np.array(
    [
        [1,2],
        [3,4]
    ]
)

array([[1, 2],
       [3, 4]])

In [8]:
np.array(
    [1, 2, 3],
    ndmin=2
)

array([[1, 2, 3]])

In [13]:
x=np.array(
    [1, 2, 3],
    dtype=complex
)

dir(x)

np.ndarray.shape

<attribute 'shape' of 'numpy.ndarray' objects>

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [ ]:
import numpy as np

x = np.array(
    [1,2,3,4]
)

x.shape



(4,)

In [ ]:
y = np.zeros(
    (2,3,4)
)

y.shape

y.shape = (3,8)



Signature:       np.shape(a)
Call signature:  np.shape(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function shape at 0x000001BFA877A520>
File:            c:\users\kaise\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Source:         
@array_function_dispatch(_shape_dispatcher)
def shape(a):
    """
    Return the shape of an array.

    Parameters
    ----------
    a : array_like
        Input array.

    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.

    See Also
    --------
    len : ``len(a)`` is equivalent to ``np.shape(a)[0]`` for N-D arrays with
          ``N>=1``.
    ndarray.shape : Equivalent array method.

    Examples
    --------
    >>> import numpy as np
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 3]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()

    >>> a = np.array([(1, 2), (3, 4), (5,

In [19]:
np.shape(0)

()

In [22]:
import numpy as np

np.ndim([[1,2,3],[4,5,6]])


np.ndim(
    np.array(
        [
            [1,2,3],
            [4,5,6]
        ]
    )
)


np.ndim(1)

0

In [ ]:
import numpy as np

a = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

a.size


np.size(a,1)

type(a)

type(a)

numpy.ndarray

In [ ]:
import numpy as np

y = np.array(
    [1,2,3],
    dtype=int,
    ndmin=2
)

y

array([[1, 2, 3]])

In [34]:
a = np.arange(6).reshape(
    (3,2)
)

a

np.reshape(a,(2,3))


a.reshape(2,3)


a.flatten()



array([0, 1, 2, 3, 4, 5])

In [2]:
a=np.array(
    [
        [1,2],
        [3,4]
    ]
)

a

a.flatten()

a.flatten(order='F')

help(a.flatten)

Help on built-in function flatten:

flatten(...) method of numpy.ndarray instance
    a.flatten(order='C')

    Return a copy of the array collapsed into one dimension.

    Parameters
    ----------
    order : {'C', 'F', 'A', 'K'}, optional
        'C' means to flatten in row-major (C-style) order.
        'F' means to flatten in column-major (Fortran-
        style) order. 'A' means to flatten in column-major
        order if `a` is Fortran *contiguous* in memory,
        row-major order otherwise. 'K' means to flatten
        `a` in the order the elements occur in memory.
        The default is 'C'.

    Returns
    -------
    y : ndarray
        A copy of the input array, flattened to one dimension.

    See Also
    --------
    ravel : Return a flattened array.
    flat : A 1-D flat iterator over the array.

    Examples
    --------
    >>> import numpy as np
    >>> a = np.array([[1,2], [3,4]])
    >>> a.flatten()
    array([1, 2, 3, 4])
    >>> a.flatten('F')
    array([1, 3

In [16]:
import numpy as np
from zstandard import DICT_TYPE_AUTO
a = np.array([
    [1,4],
    [3,1]
])

a


np.sort(a)

# a

b  = np.array([
    [3,2],
    [2,3]
])

np.sort(b,axis=1)

np.sort(a,axis=None)

dtype = [
    ('name','S10'),
    ('height','float'),
    ('age','int')
]

values = [
    ('sohel',1.8,22),
    ('harish',1.9,38),
    ('galahad',1.7,38)
]


x = np.array(values, dtype =dtype)

x

np.sort(x,order='height')

np.sort(x,order=['age','height'])

array([(b'sohel', 1.8, 22), (b'galahad', 1.7, 38), (b'harish', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [ ]:
import numpy as np

a = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

b = np.array(
    [
        [5, 6]
    ]
)

np.concatenate(
    (a,b),
    axis = 0
)

np.concatenate(
    (a, b.T),
    axis = 1
)

np.concatenate(
    (a, b),
    axis = None
)



array([1, 2, 3, 4, 5, 6])

In [ ]:
from numpy import newaxis


a = np.array(
    [1, 2, 3, 4, 5, 6]
)


a

a.shape

a2 = a[np.newaxis, :]

a2.shape

col_vector = a[:,np.newaxis]

col_vector

col_vector.shape



(6, 1)

In [33]:
data = np.array(
    [1, 2, 3]
)

data

data.shape

data[1]

data[0:2]

data[1:]


array([2, 3])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

a


a[a<5]

five_up = (a >=5)
a[five_up]

divisible_by_two = a[a%2 == 0]

divisible_by_two

c = ((a > 2) & (a < 11))

a[c]




array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
import numpy as np

x = np.array(
    [
        [3,0,0],
        [0,4,0],
        [5,6,0]
    ]
)

x


np.nonzero(x)

x[np.nonzero(x)]

np.transpose(np.nonzero(x))

array([[0, 0],
       [1, 1],
       [2, 0],
       [2, 1]])

In [ ]:
a = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

a

a > 3


np.nonzero((a>3))


a[np.nonzero((a>3))]



array([4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


a

arr1 = a[3:8]

arr1

type(arr1)





numpy.ndarray

In [55]:
a = np.array(
    [1,2,3]
)

b=np.array(
    [4,5,6]
)

np.vstack((a,b))

a = np.array(
    [
        [1],[2],[3]
    ]
)

b=np.array(
    [
        [4],[5],[6]
    ]
)

(a,b)

np.vstack((a,b))


np.hstack((a,b))


array([[1, 4],
       [2, 5],
       [3, 6]])

In [57]:
x = np.arange(1, 25).reshape(2, 12)

x

np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [62]:
x  =np.arange(9.0)

x

np.split(x, 3)

x = np.arange(8.0)

np.split(x,[3,5,6,10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [66]:
import numpy as np

x = np.arange(16.0).reshape(4,4)

x

np.hsplit(x,2)

np.hsplit(x,np.array([3,6]))


x = np.array([0,1,2,3,4,5])

np.hsplit(x,2)



[array([0, 1, 2]), array([3, 4, 5])]

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

a

b1 = a[0,:]

b1

b1[0] = 99

b1

a

# slicing -> views



array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
data = np.array(
    [1.0,2.0]
)

data * 1.6

array([1.6, 3.2])

In [ ]:
data = np.array(
    [1,2,3]
)

np.max(data)


np.min(data)

np.sum(data)



np.int64(6)