In [1]:
import numpy as np

print(np.__version__)

2.3.5


In [5]:
arr = np.array(
    [10,20,30]
)

arr

print(arr)

[10 20 30]


In [4]:
arr = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
]



)

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
arr = np.array((1,2,3))

print(arr)

[1 2 3]


In [ ]:
arr =  np.array(
    [1,2.5,3]
)

print(arr)

[1.  2.5 3. ]


In [10]:
arr1 = np.array(
    [1,2,3]
)

arr2 =np.array(arr1)

print(arr2)

[1 2 3]


In [ ]:
arr = np.array(
    [
        [10,20,30],
        [40,50,60]
    ]
)

# print(arr)
arr.ndim
arr.shape
arr.size
arr.dtype
arr.itemsize
arr.nbytes




48

In [ ]:
np.array([1,2,3]).ndim
np.array([1,2,3]).shape

(3,)

In [19]:
arr = np.array(
    [10,20,30]
)

arr.dtype

dtype('int64')

In [20]:
np.array([1.5,2.5]).dtype

dtype('float64')

In [22]:



arr = np.array(
    [
        True,False,True
    ]
)

arr.dtype


dtype('bool')

In [ ]:
arr =np.array(
    [1,2,3],
    dtype=np.float64
)

print(arr)
print(arr.dtype)



[1. 2. 3.]
float64


In [ ]:
arr = np.array(
    [1,2,3]
)

new_arr = arr.astype(float)

print(new_arr)
print(new_arr.dtype)



[1. 2. 3.]
float64


In [26]:
arr = np.array(
    [0,1,2,-3]
)

print(arr.astype(bool))

[False  True  True  True]


In [28]:
arr = np.array(
    [1,2,3]
)

print(arr.astype(str))

['1' '2' '3']


In [30]:
arr = np.array([10,20,30])

arr2 = arr

arr2[0] = 100

print(arr)
print(arr2)

[100  20  30]
[100  20  30]


In [32]:
arr = np.array([10,20,30])

arr2 = arr.copy()

arr2

arr2[0] = 100

arr2

array([100,  20,  30])

In [36]:
arr = np.array(
    [10,20,30]
)

arr2 = arr.view()

arr2

print(arr2.base)

c = arr.copy()

print(c.base)


[10 20 30]
None


In [40]:
arr = np.array(
    [10,20,30,40,50]
)

print(arr[0])
print(arr[2])

arr[1] = 200

print(arr)

10
30
[ 10 200  30  40  50]


In [ ]:
import numpy as np

arr = np.array(
    [10,20,30,40,50]
)

print(arr[-1])
print(arr[-2])
arr[-1] = 999

print(arr)



50
40
[ 10  20  30  40 999]


In [46]:
arr = np.array(
    [
        [85,90,78],
        [92,88,95],
        [76,80,84]
    ]
)

arr[0,0]

arr[0,1] = 100
print(arr)

[[ 85 100  78]
 [ 92  88  95]
 [ 76  80  84]]


In [53]:
arr = np.array(
    [10,20,30,40,50,60]
)

arr[1:4]
arr[:3]
arr[2:]
arr[:]
arr[::2]
arr[::3]
arr[::-1]

array([60, 50, 40, 30, 20, 10])

In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

arr[:2,:]



array([[10, 20, 30],
       [40, 50, 60]])

In [56]:
marks = np.array(
    [85,92,78,95,88]
)

marks > 90

marks[marks > 90]

array([92, 95])

In [ ]:
arr = np.array(
    [
        [10,20,30],
        [40,50,60]
    ]
)


cond = arr>30

cond

arr[cond]


array([40, 50, 60])

In [ ]:
marks = np.array(
    [85,92,78,95,88]
)

marks[marks < 90] = 0

print(marks)



[ 0 92  0 95  0]


In [61]:
marks = np.array([50,75,90,95,100])

marks[(marks >=80)  &(marks <=95)]

array([90, 95])

In [66]:
arr = np.array([10,20,30,40,50])

arr[[0,2,4]]

arr[[4,0,2]]

arr[[1,1,3]]

indices = np.array([0,2,4])

arr[indices]

array([10, 30, 50])

In [69]:
arr = np.array(
    [
        [10,20,30],
        [40,50,60],
        [70,80,90]
    ]
)

# row 0 and row 2

arr[[0,2]]

arr[:,[0,2]]


arr[[0,1,2],[0,2,1]]

array([10, 60, 80])

In [ ]:
arr = np.array(
    [10,20,30]
)

part =  arr[[0,2]]

part[0]=999


print(arr)

print(part)



[10 20 30]
[999  30]


In [79]:
arr = np.array(
    [1,2,3,4,5,6]
)

print(arr)

arr.shape


new_arr = arr.reshape(2,3)

print(new_arr)

new_arr.shape

arr.reshape(2,-1)

arr

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

In [ ]:
arr = np.array(
    [1,2,3,4]
)

new_arr = arr.reshape(2,2)

new_arr[0,1]=6

new_arr

arr




array([1, 6, 3, 4])

In [90]:
from sympy import primitive


arr = np.array(
    [
        [10,20,30],
        [40,50,60]
    ]
)

print(arr)

flat = arr.flatten()

# flat

# flat[0]= 999

# print(flat)

# print(arr)


rav = arr.ravel()

print(rav)

rav[0] = 999

print(rav)
print(arr)

arr.reshape(-1)

[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]
[999  20  30  40  50  60]
[[999  20  30]
 [ 40  50  60]]


array([999,  20,  30,  40,  50,  60])

In [94]:
arr = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print(arr)
arr.shape

arr.T

arr.transpose()

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
arr = np.array([1,2,3,4,5,6])

print(arr)

arr.reshape(2,3)

new_arr = np.resize(arr,(4,2))

new_arr



[1 2 3 4 5 6]


array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2]])

In [99]:
arr = np.array([1,2,3,4])

arr.resize((2,2))

print(arr)

[[1 2]
 [3 4]]


In [100]:
a = np.array([1,2,3])

b= np.array([4,5,6])


result = np.concatenate((a,b))

print(result)

[1 2 3 4 5 6]


In [102]:
a =np.array(
    [
        [1,2],
        [3,4]
    ]
)

b =np.array(
    [
        [5,6],
        [7,8]
    ]
)

np.concatenate((a,b),axis=0)

KeyboardInterrupt: 

In [3]:
import numpy as np
a = np.array(
    [1,2,3]
)


b=np.array(
    [4,5,6]
)

result = np.vstack((a,b))

print (result)

[[1 2 3]
 [4 5 6]]


In [4]:
ages = np.array([25, 30, 35])

salaries = np.array([50000, 60000, 70000])

result = np.column_stack((ages,salaries))

print(result)

[[   25 50000]
 [   30 60000]
 [   35 70000]]


In [5]:
arr = np.array([1,2,3,4,5,6])


parts = np.split(arr,3)

print(parts)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [6]:
arr = np.array(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8]
    ]
)

np.split(arr,2,axis=0)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [7]:
arr=np.array([1,2,3,4,5])

np.array_split(arr,2)

[array([1, 2, 3]), array([4, 5])]

In [8]:
arr = np.array([1,2,3])

arr + 10

array([11, 12, 13])

In [ ]:
marks = np.array(
    [60,85,90,75,95]
)

marks > 80

marks < 95

(marks > 80) & (marks < 95)

~(marks > 80)



array([ True, False, False,  True, False])

In [ ]:
arr = np.array([1,4,9,16])

np.sqrt(arr)



array([1., 2., 3., 4.])

In [14]:
arr = np.array([0,1,2])

np.exp(arr)

array([1.        , 2.71828183, 7.3890561 ])

In [16]:
arr = np.array([1,np.e,np.e**2])

print(arr)

np.log(arr)

[1.         2.71828183 7.3890561 ]


array([0., 1., 2.])

In [17]:
np.log(np.array([-1]))

C:\Users\kaise\AppData\Local\Temp\ipykernel_18552\644249099.py:1: RuntimeWarning: invalid value encountered in log
  np.log(np.array([-1]))


array([nan])

In [18]:
arr = np.array([-5,3,-10])

np.abs(arr)

array([ 5,  3, 10])

In [19]:
angles = np.array([0,np.pi/2,np.pi])

np.sin(angles)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [20]:
degrees = np.array([0,90,180])

radians = np.deg2rad(degrees)

np.sin(radians)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [ ]:
arr =np.array([3.14159,2.71828])

np.round(arr,2)




array([3.14, 2.72])

In [23]:
arr = np.array([3.9,2.1])

np.floor(arr)

np.ceil(arr)

array([4., 3.])

In [ ]:
a = np.array([1,5,3])

b=np.array([2,4,6])

np.maximum(a,b)
np.minimum(a,b)



array([1, 4, 3])

In [ ]:
marks = np.array([85, 90, 78, 92, 95])

np.sum(marks)

np.mean(marks)

np.median(marks)

arr =np.array([10,20,30,40])

np.median(arr)

np.min(marks)

np.max(marks)

np.std(marks)



np.float64(5.966573556070519)

In [ ]:
import numpy as np

marks = np.array([
    [80, 90, 85],
    [75, 88, 92],
    [95, 70, 78]
])

np.sum(marks,axis=0)
np.sum(marks,axis=1)



array([255, 255, 243])

In [ ]:
arr =np.array([92,78,85,95,80])

np.sort(arr)



array([78, 80, 85, 92, 95])

In [37]:
arr =np.array([92,78,85])

sorted_arr = np.sort(arr)

arr

sorted_arr

array([78, 85, 92])

In [38]:
arr =np.array([92,78,85])

arr.sort()

print(arr)

[78 85 92]


In [39]:
names = np.array(["Rahul", "Anita", "Vikram"])

np.sort(names)

array(['Anita', 'Rahul', 'Vikram'], dtype='<U6')

In [40]:
arr = np.array([True, False, True])

np.sort(arr)

array([False,  True,  True])

In [41]:
arr = np.array([
    [3, 1, 2],
    [9, 7, 8]
])

np.sort(arr,axis =0)

array([[3, 1, 2],
       [9, 7, 8]])

In [42]:
arr = np.array([
    [9, 1, 8],
    [3, 7, 2]
])

np.sort(arr,axis=0)

array([[3, 1, 2],
       [9, 7, 8]])

In [ ]:
arr = np.array([92, 78, 85])

np.sort(arr)[::-1]
# reverse sort

array([92, 85, 78])

In [ ]:
scores =np.array([92,78,85,95])

scores.argsort()


idx = scores.argsort()

print(idx)

students = np.array([
    "Alice",
    "Bob",
    "Charlie",
    "David"
])

students[idx]


scores.argsort()[::-1]



[1 2 0 3]


array([3, 0, 2, 1])

In [ ]:
marks =np.array([35,82,28,91,76])

np.where(marks<40)



(array([0, 2]),)

In [52]:
arr = np.array(
    [
        [10,50],
        [70,20]
    ]
)

arr < 30

np.where(arr <30)

(array([0, 1]), array([0, 1]))

In [55]:
marks =np.array(
    [35,82,28,91]
)

np.where(marks<40,40,marks)

temps = np.array([-5,3,-2,7])

np.where(temps<0,0,temps)

array([0, 3, 0, 7])

In [56]:
marks =np.array(
    [35,82,28,91]
)

np.where(marks>=40,"pass","fail")

array(['fail', 'pass', 'fail', 'pass'], dtype='<U4')

In [57]:
arr =np.array(
    [1,2,3,4]
)

np.where(arr %2==0,100,arr)

array([  1, 100,   3, 100])

In [ ]:
arr =np.array([5,0,8,0,12,0])

np.nonzero(arr)

arr[np.nonzero(arr)]



array([ 5,  8, 12])

In [60]:
arr = np.array(
    [
        [1,0,3],
        [0,5,0]
    ]
)

np.nonzero(arr)

(array([0, 0, 1]), array([0, 2, 1]))

In [61]:
arr =np.array(
    [3,1,2,3,2,1,4]
)

np.unique(arr)

array([1, 2, 3, 4])

In [ ]:
grades =np.array(["A","B","A","c","B"])

np.unique(grades)



array(['A', 'B', 'c'], dtype='<U1')

In [ ]:
# counting occurences

arr =np.array(
    [3,1,2,3,2,1,4]
)

values,counts =np.unique(arr,return_counts=True)

print(values)
print(counts)

np.unique(arr,return_index=True)

np.unique(arr,return_inverse=True)

np.unique(arr,return_counts=True)



[1 2 3 4]
[2 2 2 1]


(array([1, 2, 3, 4]), array([2, 2, 2, 1]))

: 

In [ ]:
sales =np.array(
    [120,180,150,220,190]
)

np.argmax(sales)


In [3]:
import numpy as np
arr = np.array(
    [
        [10,30,20],
        [50,40,60]
    ]
)

np.argmax(arr)
np.argmax(arr,axis=1)

array([1, 2])

In [ ]:
np.random

np.random.random()
np.random.random(5)

np.random.random((2,3))


array([[0.65105341, 0.04733858, 0.51685955],
       [0.58678518, 0.54399119, 0.55049521]])

In [ ]:
np.random.random(3)

np.random.seed(42)

print(np.random.random(3))

print(np.random.random(3))

rng = np.random.default_rng(42)

np.random.seed(42)




[0.37454012 0.95071431 0.73199394]
[0.59865848 0.15601864 0.15599452]


In [17]:
np.random.seed(42)

np.random.random(3)

np.random.seed(42)

np.random.random(3)

array([0.37454012, 0.95071431, 0.73199394])

In [20]:
# np.random.randit(low,high,size)

np.random.randint(1,6)
np.random.randint(1,10,size=5)
np.random.randint(0,10,size=(2,3))

array([[1, 7, 5],
       [1, 4, 0]], dtype=int32)

In [21]:
np.random.randint(0,2,size=10)

array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0], dtype=int32)

In [24]:
np.random.seed(42)
np.random.randint(1,7,size=5)

np.random.seed(42)

np.random.randint(1,7,size=5)

array([4, 5, 3, 5, 5], dtype=int32)

In [30]:
# np.random(a,size=None,replace=True,p=None)

students = np.array(
    [
        "alice",
        "bob",
        "charlie",
        "david"
    ]
)

np.random.choice(students)
np.random.choice(students,size=3)

np.random.choice(students,size=3,replace=False)
np.random.choice(
    ["heads","tails"],
    size=10
)

np.random.choice(
    [1,2,3,4,5,6],
    size=10
)

np.random.choice(
    ["heads","tails"],
    size=10,
    p=[0.8,0.2]
)



array(['heads', 'tails', 'tails', 'heads', 'tails', 'heads', 'heads',
       'heads', 'heads', 'heads'], dtype='<U5')

In [ ]:
students =np.array(
    [
        "alice",
        "bob",
        "charlie",
        "david"
    ]
)

np.random.shuffle(students)

print(students)

# np.random.permutation() shuffled copy

shuffled = np.random.permutation(students)

shuffled

np.random.permutation(5)




['bob' 'alice' 'charlie' 'david']


array([1, 3, 0, 4, 2], dtype=int32)

In [36]:
arr = np.array(
    [
        [1,2],
        [3,4],
        [5,6]
    ]
)

np.random.shuffle(arr)
print(arr)

[[5 6]
 [3 4]
 [1 2]]


In [39]:
np.random.seed(42)

ages =np.random.randint(17,23,size=5)

print(ages)

marks = np.random.randint(0,101,size=5)

print(marks)

attendence = np.random.randint(70,101,size=5)

print(attendence)

[20 21 19 21 21]
[82 86 74 74 87]
[90 73 77 93 72]


In [40]:
a = np.array([1,2,3])
b=np.array([4,5,6])

np.dot(a,b)

np.int64(32)

In [ ]:
marks = np.array(
    [
        [80,90],
        [70,85]
    ]
)

marks.shape



(2, 2)

In [46]:
A =np.array(
    [
        [1,2],
        [3,4]
    ]
)

B = np.array(
    [
        [5,6],
        [7,8]
    ]
)

A.shape
B.shape

np.dot(A,B)

A@B

array([[19, 22],
       [43, 50]])

In [ ]:
np.eye(3)

A=np.array(
    [
        [2,3],
        [4,5]
    ]
)

I =np.eye(2)

A@I==I@A


array([[ True,  True],
       [ True,  True]])

In [ ]:
marks =np.array(
    [
        [80,90,85],
        [70,88,92]
    ]
)

marks.shape

(2, 3)

In [53]:
A=np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

A.T

np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
a=np.array([1,2,3])
a.T

array([1, 2, 3])

In [55]:
a=np.array(
    [1,2,3]
)

a.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [57]:
A=np.array(
    [
        [2,3],
        [1,4]
    ]
)

# np.det(A)
np.linalg.det(A)

np.float64(5.000000000000001)

In [59]:
A=np.array(
    [
        [1,2],
        [3,4]
    ]
)

np.linalg.inv(A)
A@np.linalg.inv(A)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [63]:
A=np.array(
    [
        [1,2],
        [2,4]
    ]
)

np.linalg.det(A)
# np.linalg.inv(A)

np.float64(0.0)

In [66]:
A=np.array([
    [2,0],
    [0,3]
]
)

values,vectors=np.linalg.eig(A)

print(values)
print(vectors)

[2. 3.]
[[1. 0.]
 [0. 1.]]


In [67]:
import time
start =time.time()

end=time.time()

print(end-start)

0.00010371208190917969


In [69]:
students =np.array(
    [
        [18,85,90],
        [19,76,88],
        [17,92,95],
        [18,60,80]
    ]
)


students[:,1]
students[:,2]

array([90, 88, 95, 80])