In [3]:
import numpy as  np

a = np.array([1,2,3])

print(a)

[1 2 3]


In [7]:
import numpy as np

a = np.array([[1.,2.,1.],
             [2.,3.,1.]])

print(a)


a.shape

[[1. 2. 1.]
 [2. 3. 1.]]


(2, 3)

In [9]:
import numpy as np

a = np.array(
    [1,2,3],
    dtype= np.float32
)


print(a.dtype)

a.itemsize

float32


4

In [ ]:
data = np.array([[1.5, -0.1, 3],
                 [0, -3, 6.5]])

data * 10

data + data

data.shape

data.dtype

b  = np.array([
    [1,2],
    [3,4]
])

print(b)

b.shape

b.dtype



[[1 2]
 [3 4]]


dtype('int64')

In [19]:
a = [1,2,3]

a * 10

[1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3]

In [ ]:
np.array([1, 2, 3])



array([1, 2, 3])

In [ ]:
# 1. Creating Arrays with np.array()

import numpy as np


data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

print(arr1)

arr1.dtype

arr1.size

arr1.ndim

arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])


arr2

arr2.dtype

arr2.size

arr2.ndim

arr2.shape

np.zeros(9)

# np.zeros Creates arrays filled with zeros.

np.zeros((1,2))

np.zeros((5,7))

np.ones((2,3))

np.empty((1,2,2))

"""
np.empty faster than np.zeros  foro overwriting with zero 
"""

np.empty((2, 3, 2))

np.arange(16) 

"""
np.arange  is like range  
"""

np.arange(0,10, 2)


""" 
np.arange(start, stop, step)
"""








[6.  7.5 8.  0.  1. ]


array([0, 2, 4, 6, 8])

In [1]:
import numpy as np

# Creating NumPy arrays with explicit data types (dtype)

arr = np.array(
    [1, 2, 3],
    dtype=np.int32
)

print(arr)
print(arr.dtype)


arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)


# Original integer array
c = np.array([1, 2, 3, 4, 5])

# Convert integer array to float64 using astype()
float_c = c.astype(np.float64)

print(float_c)
print(float_c.dtype)


"""
NumPy dtype Notes
-----------------

dtype
-----
dtype stands for "data type".

It defines:
- how NumPy stores values in memory
- memory size of each element
- type of operations performed

Examples:
- np.int32   -> 32-bit integer
- np.float64 -> 64-bit floating point number


astype()
--------
Syntax:
    array.astype(new_dtype)

Purpose:
- Converts an array from one datatype to another.

Important:
- astype() creates and returns a NEW array.
- Original array remains unchanged.


Example:
--------
a = np.array([1, 2, 3])

b = a.astype(np.float64)

Result:
- a.dtype -> int64/int32
- b.dtype -> float64


Type Conversion Behavior
------------------------
NumPy does NOT round values during integer conversion.

It truncates toward zero.

Example:
--------
x = np.array([1.9, -2.7, 3.5])

x.astype(np.int32)

Output:
array([ 1, -2,  3], dtype=int32)
"""

[1 2 3]
int32
float64
int32
[1. 2. 3. 4. 5.]
float64


'\nNumPy dtype Notes\n-----------------\n\ndtype\n-----\ndtype stands for "data type".\n\nIt defines:\n- how NumPy stores values in memory\n- memory size of each element\n- type of operations performed\n\nExamples:\n- np.int32   -> 32-bit integer\n- np.float64 -> 64-bit floating point number\n\n\nastype()\n--------\nSyntax:\n    array.astype(new_dtype)\n\nPurpose:\n- Converts an array from one datatype to another.\n\nImportant:\n- astype() creates and returns a NEW array.\n- Original array remains unchanged.\n\n\nExample:\n--------\na = np.array([1, 2, 3])\n\nb = a.astype(np.float64)\n\nResult:\n- a.dtype -> int64/int32\n- b.dtype -> float64\n\n\nType Conversion Behavior\n------------------------\nNumPy does NOT round values during integer conversion.\n\nIt truncates toward zero.\n\nExample:\n--------\nx = np.array([1.9, -2.7, 3.5])\n\nx.astype(np.int32)\n\nOutput:\narray([ 1, -2,  3], dtype=int32)\n'

In [1]:
import numpy as np

x = np.array([1,2,3])

print(x)

[1 2 3]


In [ ]:
np.array([-1, 2, 3],
         dtype=np.int8
         
         )

"""
int8 is signed integer data type 

both positive and negative numbers
"""

array([-1,  2,  3], dtype=int8)

In [3]:
np.array(
    [0, 1, 255],
    dtype=np.uint8

)

array([  0,   1, 255], dtype=uint8)

In [ ]:
a = np.array(
    [1.5, 2.7],
    dtype = np.float32
    )


a



"""
less precision for float32 
"""


array([1.5, 2.7], dtype=float32)

In [7]:
a = np.array(
    [1.5, 2.7],
    dtype=np.float64

)


a

array([1.5, 2.7])

In [8]:
b = np.array(
    [True, False, True],
    dtype=bool
)

print(b)

[ True False  True]


In [10]:
s = np.array(
    ["cat", "dog"],
    dtype='S10'
)

print(s)

[b'cat' b'dog']


In [11]:
arr = np.array(
    [1, 2, 3],
    dtype=np.int32


)

print(arr)

[1 2 3]


In [ ]:
a = np.array(
    ["1", "2", "hello"]
)

a.astype(np.float64)



``

ValueError: could not convert string to float: np.str_('hello')

In [ ]:
import numpy as np

int_array = np.arange(10)

# print(int_array)

int_array

calibers = np.array(
    [.22, .270, .357, .380, .44, .50],
    dtype=np.float64
)


calibers

converted = int_array.astype(calibers.dtype)


int_array

converted

converted.dtype

dtype('float64')

In [ ]:
"""" as type always createas a copy
"""



In [35]:
"""
========================================================
Arithmetic with NumPy Arrays
========================================================

One of the biggest advantages of NumPy is:

    Vectorization

Vectorization means:
    Performing operations on entire arrays at once
    without writing explicit Python loops.

Advantages:
    • Faster
    • Cleaner syntax
    • Memory efficient
"""

import numpy as np


# ======================================================
# Creating a 2D NumPy Array
# ======================================================

arr = np.array(
    [
        [1.0, 2.0, 3.0],
        [4.0, 5.0, 6.0]
    ]
)

print("Array:\n", arr)

print("\nShape of array:")
print(arr.shape)


# ======================================================
# Element-wise Arithmetic Operations
# ======================================================

# Multiplication (element by element)
print("\nElement-wise multiplication:")
print(arr * arr)

# Subtraction
# Every element subtracts itself
print("\nElement-wise subtraction:")
print(arr - arr)


# ======================================================
# Scalar Operations
# ======================================================

"""
Scalar:
    A single number.

NumPy automatically applies the scalar
to every element in the array.

This mechanism is called:
    Broadcasting
"""

print("\nScalar division:")
print(1 / arr)

print("\nPower operation:")
print(arr ** 2)


# ::contentReference[oaicite:0]{index=0}



# ======================================================
# Comparison Operations
# ======================================================

arr2 = np.array(
    [
        [0.0, 4.0, 1.0],
        [7.0, 2.0, 12.0]
    ]
)

print("\nSecond array:\n", arr2)

# Element-wise comparison
print("\nComparison (arr2 > arr):")
print(arr2 > arr)


# ======================================================
# Boolean Indexing / Filtering
# ======================================================

"""
Boolean arrays are heavily used for:
    • Filtering
    • Masking
    • Conditions
"""

print("\nElements greater than 3:")
print(arr[arr > 3])


# ======================================================
# Matrix Multiplication
# ======================================================

"""
Element-wise multiplication:
    arr * arr

Matrix multiplication:
    arr @ arr.T
"""

print("\nMatrix multiplication using @ operator:")
print(arr @ arr.T)

print("\nMatrix multiplication using np.dot():")
print(np.dot(arr, arr.T))


# ======================================================
# Broadcasting Examples
# ======================================================

# Scalar broadcasting
print("\nBroadcasting with scalar:")
print(arr + 10)

# Array broadcasting
print("\nBroadcasting with 1D array:")
print(arr + np.array([1, 2, 3]))


# ======================================================
# Mental Model
# ======================================================

"""
Think of NumPy arithmetic as:

    Parallel operations on entire blocks of memory

instead of:
    • Python loops
    • One element at a time

This is why NumPy is extremely fast.
"""

Array:
 [[1. 2. 3.]
 [4. 5. 6.]]

Shape of array:
(2, 3)

Element-wise multiplication:
[[ 1.  4.  9.]
 [16. 25. 36.]]

Element-wise subtraction:
[[0. 0. 0.]
 [0. 0. 0.]]

Scalar division:
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

Power operation:
[[ 1.  4.  9.]
 [16. 25. 36.]]

Second array:
 [[ 0.  4.  1.]
 [ 7.  2. 12.]]

Comparison (arr2 > arr):
[[False  True False]
 [ True False  True]]

Elements greater than 3:
[4. 5. 6.]

Matrix multiplication using @ operator:
[[14. 32.]
 [32. 77.]]

Matrix multiplication using np.dot():
[[14. 32.]
 [32. 77.]]

Broadcasting with scalar:
[[11. 12. 13.]
 [14. 15. 16.]]

Broadcasting with 1D array:
[[2. 4. 6.]
 [5. 7. 9.]]


'\nThink of NumPy arithmetic as:\n\n    Parallel operations on entire blocks of memory\n\ninstead of:\n    • Python loops\n    • One element at a time\n\nThis is why NumPy is extremely fast.\n'

In [77]:
"""
========================================================
NumPy Indexing and Slicing
========================================================

Topics Covered:
    • 1D indexing
    • Slicing
    • Slice views vs copies
    • 2D indexing
    • 3D indexing
    • Row/column slicing
    • Broadcasting during assignment

Important Concept:
    NumPy slices are usually VIEWS, not copies.

This means:
    Modifying a slice can also modify
    the original array.
"""

import numpy as np


# ======================================================
# 1D ARRAY INDEXING
# ======================================================

# Create array from 0 to 9
arr = np.arange(10)

print("Original Array:")
print(arr)


# ------------------------------------------------------
# Accessing single element
# ------------------------------------------------------

print("\nElement at index 5:")
print(arr[5])


# ------------------------------------------------------
# Basic slicing
# ------------------------------------------------------

print("\nElements from index 5 to 7:")
print(arr[5:8])


# ------------------------------------------------------
# Assigning scalar value to slice
# ------------------------------------------------------

"""
Broadcasting occurs automatically.

The scalar value 12 is propagated
to every element in the slice.
"""

arr[5:8] = 12

print("\nAfter arr[5:8] = 12")
print(arr)


# ======================================================
# SLICES ARE VIEWS
# ======================================================

"""
arr_slice does NOT create a copy.

It creates a VIEW into the original array.
"""

arr_slice = arr[5:8]

print("\nSlice View:")
print(arr_slice)


# ------------------------------------------------------
# Modifying slice affects original array
# ------------------------------------------------------

arr_slice[1] = 12345

print("\nModified Slice:")
print(arr_slice)

print("\nOriginal Array After Slice Modification:")
print(arr)


# ------------------------------------------------------
# [:] selects entire slice
# ------------------------------------------------------

arr_slice[:] = 64

print("\nAfter arr_slice[:] = 64")
print(arr_slice)

print("\nOriginal Array:")
print(arr)


# ======================================================
# CREATING AN INDEPENDENT COPY
# ======================================================

"""
Use .copy() when you want an
independent array.
"""

copied_slice = arr[5:8].copy()

copied_slice[0] = 999

print("\nCopied Slice:")
print(copied_slice)

print("\nOriginal Array Remains Unchanged:")
print(arr)


# ======================================================
# 2D ARRAY INDEXING
# ======================================================

arr2d = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

print("\n2D Array:")
print(arr2d)


# ------------------------------------------------------
# Accessing rows
# ------------------------------------------------------

print("\nThird Row:")
print(arr2d[2])


# ------------------------------------------------------
# Accessing individual elements
# ------------------------------------------------------

print("\nUsing Recursive Indexing:")
print(arr2d[0][2])

print("\nUsing Comma-Separated Indexing:")
print(arr2d[0, 2])


# ======================================================
# 3D ARRAY INDEXING
# ======================================================

arr3d = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ]
    ]
)

print("\n3D Array:")
print(arr3d)


# ------------------------------------------------------
# Copying subarray
# ------------------------------------------------------

old_values = arr3d[0].copy()

print("\nCopied First Block:")
print(old_values)


# ------------------------------------------------------
# Assign scalar to subarray
# ------------------------------------------------------

"""
Scalar broadcasting occurs here.

Every element in arr3d[0]
becomes 42.
"""

arr3d[0] = 42

print("\nAfter arr3d[0] = 42")
print(arr3d)


# ------------------------------------------------------
# Restore original values
# ------------------------------------------------------

arr3d[0] = old_values

print("\nRestored Original Values:")
print(arr3d)


# ------------------------------------------------------
# Selecting deeper dimensions
# ------------------------------------------------------

x = arr3d[1]

print("\nSecond Block:")
print(x)

print("\nFirst Row of Second Block:")
print(x[0])


# ======================================================
# 2D ARRAY SLICING
# ======================================================

print("\nOriginal arr2d:")
print(arr2d)


# ------------------------------------------------------
# First two rows
# ------------------------------------------------------

print("\nFirst Two Rows:")
print(arr2d[:2])


# ------------------------------------------------------
# Row and column slicing
# ------------------------------------------------------

"""
arr2d[:2, 1:]

Meaning:
    • First 2 rows
    • Columns starting from index 1
"""

print("\nFirst Two Rows, Columns From Index 1:")
print(arr2d[:2, 1:])


# ======================================================
# MIXING INDEXES AND SLICES
# ======================================================

"""
Using:
    integer index + slice

reduces dimensions.
"""

lower_dim = arr2d[1, :2]

print("\nOriginal arr2d:")
print(arr2d)

print("\nLower Dimensional Slice:")
print(lower_dim)

print("\nShape of lower_dim:")
print(lower_dim.shape)


# ======================================================
# COLON (:)
# ======================================================

"""
Colon means:
    Select the entire axis
"""

print("\nAll Rows, First Column:")
print(arr2d[:, :1])


# ======================================================
# ASSIGNMENT TO SLICES
# ======================================================

"""
Assignment modifies the selected region.
"""

arr2d[:2, 1:] = 0

print("\nUpdated arr2d:")
print(arr2d)


# ======================================================
# FINAL NOTE
# ======================================================

"""
Mental Model:

NumPy indexing and slicing operate
directly on memory views.

Advantages:
    • Fast
    • Memory efficient
    • Avoids unnecessary copies

But:
    Modifying slices can affect
    the original array.
"""

Original Array:
[0 1 2 3 4 5 6 7 8 9]

Element at index 5:
5

Elements from index 5 to 7:
[5 6 7]

After arr[5:8] = 12
[ 0  1  2  3  4 12 12 12  8  9]

Slice View:
[12 12 12]

Modified Slice:
[   12 12345    12]

Original Array After Slice Modification:
[    0     1     2     3     4    12 12345    12     8     9]

After arr_slice[:] = 64
[64 64 64]

Original Array:
[ 0  1  2  3  4 64 64 64  8  9]

Copied Slice:
[999  64  64]

Original Array Remains Unchanged:
[ 0  1  2  3  4 64 64 64  8  9]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Third Row:
[7 8 9]

Using Recursive Indexing:
3

Using Comma-Separated Indexing:
3

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Copied First Block:
[[1 2 3]
 [4 5 6]]

After arr3d[0] = 42
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]

Restored Original Values:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Second Block:
[[ 7  8  9]
 [10 11 12]]

First Row of Second Block:
[7 8 9]

Original arr2d:
[[1 2 3]
 [4 5 6]
 [

'\nMental Model:\n\nNumPy indexing and slicing operate\ndirectly on memory views.\n\nAdvantages:\n    • Fast\n    • Memory efficient\n    • Avoids unnecessary copies\n\nBut:\n    Modifying slices can affect\n    the original array.\n'

In [94]:
"""
========================================================
NumPy Boolean Indexing
========================================================

Boolean indexing allows you to:

    • Filter data using conditions
    • Select specific rows/columns
    • Modify values conditionally

Core Idea:
    Comparisons on NumPy arrays are vectorized.

This means:
    Operations happen element-wise
    without explicit Python loops.
"""

import numpy as np


# ======================================================
# SAMPLE DATA
# ======================================================

names = np.array(
    ["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"]
)

data = np.array(
    [
        [4, 7],
        [0, 2],
        [-5, 6],
        [0, 0],
        [1, 2],
        [-12, -4],
        [3, 4]
    ]
)

print("Names Array:")
print(names)

print("\nData Array:")
print(data)


# ======================================================
# BOOLEAN COMPARISON
# ======================================================

"""
Comparison operations are vectorized.

Each element is compared individually.
"""

print("\nnames == 'Bob'")
print(names == "Bob")


# ======================================================
# BOOLEAN INDEXING
# ======================================================

"""
Boolean arrays can be used as indexes.

Only rows where condition is True
are selected.
"""

print("\nRows where name is 'Bob':")
print(data[names == "Bob"])


# ======================================================
# ROW + COLUMN SELECTION
# ======================================================

print("\nRows where name is 'Bob', columns from index 1:")
print(data[names == "Bob", 1:])

print("\nRows where name is 'Bob', only column index 1:")
print(data[names == "Bob", 1])


# ======================================================
# NEGATION
# ======================================================

"""
!= means:
    Not equal

~ means:
    Logical NOT / inversion
"""

print("\nNames not equal to 'Bob':")
print(names != "Bob")

print("\nNegating condition using ~:")
print(~(names == "Bob"))


print("\nRows where name is NOT 'Bob':")
print(data[~(names == "Bob")])


# ======================================================
# USING CONDITION VARIABLES
# ======================================================

cond = names == "Bob"

print("\nStored Boolean Condition:")
print(cond)

print("\nUsing condition variable:")
print(data[~cond])


# ======================================================
# MULTIPLE CONDITIONS
# ======================================================

"""
Use:
    &  -> AND
    |  -> OR

Do NOT use:
    and
    or

because Python keywords do not work
with NumPy Boolean arrays.
"""

mask = (names == "Bob") | (names == "Will")

print("\nCombined Boolean Mask:")
print(mask)

print("\nRows where name is Bob OR Will:")
print(data[mask])


# ======================================================
# IMPORTANT NOTE ABOUT COPIES
# ======================================================

"""
Boolean indexing creates COPIES,
not views.

Unlike slicing:
    data[mask]

returns a new independent array.
"""


# ======================================================
# MODIFYING VALUES WITH BOOLEAN INDEXING
# ======================================================

"""
Boolean indexing can also be used
for conditional assignment.
"""

print("\nOriginal Data:")
print(data)


# ------------------------------------------------------
# Replace negative values with 0
# ------------------------------------------------------

data[data < 0] = 0

print("\nAfter replacing negative values with 0:")
print(data)


# ======================================================
# MODIFYING ENTIRE ROWS
# ======================================================

"""
Rows where condition is True
can be updated completely.
"""

data[names != "Joe"] = 7

print("\nAfter setting rows not equal to 'Joe' to 7:")
print(data)


# ======================================================
# IMPORTANT CONCEPTS SUMMARY
# ======================================================

"""
Boolean Indexing Rules
----------------------

1. Comparisons are vectorized

    names == "Bob"

2. Boolean arrays must match axis length

3. Use:
       &
       |
       ~

   instead of:
       and
       or
       not

4. Boolean indexing returns COPIES

5. Boolean indexing is powerful for:
       • Filtering
       • Data cleaning
       • Conditional updates
       • Machine Learning preprocessing
"""

Names Array:
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Data Array:
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]

names == 'Bob'
[ True False False  True False False False]

Rows where name is 'Bob':
[[4 7]
 [0 0]]

Rows where name is 'Bob', columns from index 1:
[[7]
 [0]]

Rows where name is 'Bob', only column index 1:
[7 0]

Names not equal to 'Bob':
[False  True  True False  True  True  True]

Negating condition using ~:
[False  True  True False  True  True  True]

Rows where name is NOT 'Bob':
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]

Stored Boolean Condition:
[ True False False  True False False False]

Using condition variable:
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]

Combined Boolean Mask:
[ True False  True  True  True False False]

Rows where name is Bob OR Will:
[[ 4  7]
 [-5  6]
 [ 0  0]
 [ 1  2]]

Original Data:
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]

After replacing 

'\nBoolean Indexing Rules\n----------------------\n\n1. Comparisons are vectorized\n\n    names == "Bob"\n\n2. Boolean arrays must match axis length\n\n3. Use:\n       &\n       |\n       ~\n\n   instead of:\n       and\n       or\n       not\n\n4. Boolean indexing returns COPIES\n\n5. Boolean indexing is powerful for:\n       • Filtering\n       • Data cleaning\n       • Conditional updates\n       • Machine Learning preprocessing\n'

In [ ]:
arr = np.zeros((8, 4))

arr

for i in range(8):
    arr[i] = i

arr

arr[[4, 3, 0, 6]]  

 #select arbitrary rows


# return copy

arr[[-3, -5, -7]]







array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.arange(32).reshape((8, 4))

arr

print(arr)


result = arr[
    [1, 5, 7, 2],
    [0, 3, 1, 2]
]
# select individual elements

result

arr[1,0]
arr[5,3]

# rectangular selection

# 2 step indexing

rectangular = arr[
    [1, 5, 7, 2]
][:, [0,3,1,2]]

rectangular



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [1]:
import numpy as np

In [6]:
arr = np.array(
    [1,2,3]
)

type(arr)

arr2d = np.array(
    [
        [1,2],
        [3,4]
    ]
)

type(arr2d)

arr2d

array([[1, 2],
       [3, 4]])

In [ ]:
a = np.array(
    [1,2,3,4,5,6]
)

a

a[0]

a[0]  = 10

a


a[:3]

# array slicing return view : object that refers to
# the data in original array,original array can be
# mutated

b = a[3:]

b

b[0] = 40

b

a




array([10,  2,  3, 40,  5,  6])

In [ ]:
a = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
)

a

""" axis 0 down the rows
row 0
row 1
row 2

axis 1 across the columns

col 0 col1 col2 col3


"""

a.shape

a[1,3]




np.int64(8)

In [24]:
a = np.array(
    [
        [
            [1,2,3],
            [4,5,6]


        ],

        [
            [7,8,9],
            [10,11,12]

        ]
    ]
)

a.ndim

a.shape
# we want 11

a[1, 1, 1]

# for any numpy array

# a[....,row,column]


# 0d array 1 number = scalar

"""
od array = scalar ,shape =()

1d array = vector, a=np.array(
    [1,2,3]
) 

shape =(3,)

number of valus in shape tuple = the number of dimensions

2d array = matrix

a= np.array( [[1,2],[3,4]]) matrix

3d or higheer = tensor

instead n d array is better

0d = single number
1d = line of numbers
2d = table
3d = stack of tables
3d = stack of stacks of tables


regardless of shape ,just call it array

"""

'\nod array = scalar ,shape =()\n\n1d array = vector, a=np.array(\n    [1,2,3]\n) \n\nshape =(3,)\n\nnumber of valus in shape tuple = the number of dimensions\n\n2d array = matrix\n\na= np.array( [[1,2],[3,4]]) matrix\n\n3d or higheer = tensor\n\ninstead n d array is better\n\n0d = single number\n1d = line of numbers\n2d = table\n3d = stack of tables\n3d = stack of stacks of tables\n\n\nregardless of shape ,just call it array\n\n'

In [34]:
import math
from math import prod
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

a.ndim

a.ndim

type(a.ndim)



# shape of array is tuple of non negative integers that specify the number of elements along dimension


a.shape

len(a.shape) == a.ndim

a.size 

# size = total number of elements in array 
# contained in size attribute

math.prod(a.shape)


prod([2,3,4])

prod([2,3,4], start=10)

a.dtype


dtype('int64')

In [3]:
import numpy as np
np.zeros(2)

np.ones(2)

"""# ndarray needs memorybloc ,shape,dtype

# np.empty() creates the memory block, shape, and dtype but leaves the memory contents untouched.

Give me space for 2 numbers.
# I will put the values there myself later."""

np.arange(4)


"""Think of arange() as:

"Create numbers starting from 0 up to (but not including) stop."""

np.arange(5,dtype=float)

np.shape(np.arange(5))

"""That's why arange is often described as the NumPy version of Python's range(), except it returns an actual NumPy array instead of a range object."""

"""np.arange(start, stop, step) means:

"Start at start, keep adding step, and stop before reaching stop."""

np.arange(10,0,-2)

np.linspace

# np.arange()



"""linspace() → you specify how many numbers you want
np.linspace()

You tell NumPy:

"Give me exactly 5 evenly spaced numbers from 2 to 3."

np.linspace(2, 3, num=5)"""

np.linspace(2,3,num=5)

np.linspace(2,3,num=5,endpoint=True)

np.linspace(2,3,num=5,endpoint=False)

# retstep=True

# Also return the spacing.


np.linspace(
    2,3,num=5,retstep=True
)


samples,step = np.linspace(
    2,3,num=5,retstep=True
)

samples
step


x = np.ones(2, dtype=np.int64)

x
"""
| dtype           | Meaning        | Example    |
| --------------- | -------------- | ---------- |
| `np.int64`      | Integer        | `1, 2, 3`  |
| `np.float64`    | Decimal number | `1.5, 2.7` |
| `np.bool_`      | True/False     | `True`     |
| `np.complex128` | Complex number | `3+4j`     |
"""

x.dtype



samples,step = np.linspace(
    2,3,num=5,retstep=True
)

samples
step


print(samples,step)




[2.   2.25 2.5  2.75 3.  ] 0.25


In [74]:
import numpy as np


a = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

"""a.ndim -> number of axes(dim)
"""  
np.array(5).ndim

np.array(
    [1,2,3]
).ndim

"""np.array() 

parameters

1.object
2.dtype

3.copy
4.order
5.subok
6.ndmin"""



np.array(
    [1,2,3],
    dtype=float)



# copy whether to create a copy

b=np.array(a,copy=True)

b

"""order
"""
"""| Value | Meaning                                   |
| ----- | ----------------------------------------- |
| `'C'` | Row-major order (C style)                 |
| `'F'` | Column-major order (Fortran style)        |
| `'A'` | Preserve Fortran if possible, otherwise C |
| `'K'` | Keep memory layout as close as possible   |



"""

"""The order parameter controls how a NumPy array is stored in memory, not how it is displayed.
"""


a.itemsize


c = np.array(
    [
        [1,2],
        [3,4]
    ],
    dtype=complex
)


c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [ ]:
a = np.arange(6)

a

b = np.arange(12).reshape(4,3)

b

c = np.arange(24)

c.reshape(2,3,4)





array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a = np.array(
    [20,30,40,50]
)

a

b = np.arange(4)

b

c  = a - b
c

b ** 2

10 * np.sin(a)


a < 35


"""Arithmetic operators on arrays apply elementwise"""

"""A new array is created and filled with the result."""

"""The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:"""

A = np.array(
    [
        [1,1],
        [0,1]
    ]
)


B = np.array(
    [
        [2,0],
        [3,4]
    ]
)

A * B
# A @ B  matrix mulitplication

A @ B


A.dot(B)

"""A.dot(B)
Dot product / matrix multiplication depending on dimensions"""



array([[5, 4],
       [3, 4]])

In [109]:

a = np.ones(
    (2,3),
    dtype=int
)

a
a.dtype.name

rng = np.random.default_rng()


# rng is generator object

rng.random()

rng.random(5)


rng.random((2,3))


rng.integers((1,10))

rng.integers(1,10)

rng.integers(1,10, size=(2,3))


rng.normal()


rng.normal(size=1000)

rng.choice([10,20,30,40])




np.int64(20)

In [ ]:
rg = np.random.default_rng()
type(rg)

a  = np.ones(
    (2,3),
    dtype=int
)

a
a.dtype


b =rg.random((2,3))

b
b.dtype

a*=3

a

b+=a 

b 


b.dtype


# a +=b 


# a*=b

c = a + b 

c




array([[6.85845206, 6.81678478, 6.51398894],
       [6.74814802, 6.95838092, 6.26523723]])

In [143]:
a = np.ones(3, dtype=np.int32)

a 

a.dtype.name 

from numpy import pi

b = np.linspace(0,pi,3)

b 

b.dtype.name

c = a + b 

c

c.dtype.name

d = np.exp(c * 1j)

d 
d.dtype

"""bool -> int -> float -> complex"""


a.sum()

a.min()

a.max()

np.int32(1)

In [ ]:
a = np.array([
    [0.82770259, 0.40919914, 0.54959369],
    [0.02755911, 0.75351311, 0.53814331]
])

a.shape

a.sum()

a.sum().shape

a.sum()


a.min()

a.max()




np.float64(0.82770259)

In [162]:
b = np.arange(12).reshape(3,4)

b 


b.shape

"""axis 0 move down rows

axis 1 move across columns"""

b 
print(b)
b.sum(axis=0)

b.min(axis=1)

b.cumsum(axis=1)


b.sum(axis=0)




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(arr)

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a,b))

np.concatenate

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6]])

res = np.concatenate((a,b), axis=0)

print(a.shape)

print(b.shape)

print(res.shape)

out = np.empty((3,2))



np.concatenate([a,b], out=out)

out.dtype




(2, 2)
(1, 2)
(3, 2)


dtype('float64')

In [ ]:
out = np.empty((4,),dtype=int)



np.concatenate(([1,2],[3,4]),out=out)

print(out)


# All dimensions must match except the concatenation axis



[1 2 3 4]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate((a,b))
# extends a existing dim

np.stack((a, b)) 
# stack creates a new dim





array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a,b))

print(result)

print(result.shape)





[1 2 3 4 5 6]
(6,)


In [ ]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])

np.concatenate((a,b),axis=0).shape





(2, 2)

In [ ]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5],
              [6]])

np.concatenate((a,b), axis=1)

In [4]:
np.array??



Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [8]:
import numpy as np

import inspect

np.array.__doc__

"array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,\n          like=None)\n\n    Create an array.\n\n    Parameters\n    ----------\n    object : array_like\n        An array, any object exposing the array interface, an object whose\n        ``__array__`` method returns an array, or any (nested) sequence.\n        If object is a scalar, a 0-dimensional array containing object is\n        returned.\n    dtype : data-type, optional\n        The desired data-type for the array. If not given, NumPy will try to use\n        a default ``dtype`` that can represent the values (by applying promotion\n        rules when necessary.)\n    copy : bool, optional\n        If ``True`` (default), then the array data is copied. If ``None``,\n        a copy will only be made if ``__array__`` returns a copy, if obj is\n        a nested sequence, or if a copy is needed to satisfy any of the other\n        requirements (``dtype``, ``order``, etc.). Note that any copy of\n        the da

In [9]:
import numpy as np
import inspect

print(inspect.signature(np.array))

ValueError: no signature found for builtin <built-in function array>

In [10]:
arr = np.array(
    [1,2,3]
)

dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [11]:
np.ones??



Signature: np.ones(shape, dtype=None, order='C', *, device=None, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In thi

In [12]:
np.array??

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [ ]:
a = np.array(
    [1,2]
)

a

a.shape??

help(a.shape)


Help on tuple object:

class tuple(object)
 |  tuple(iterable=(), /)
 |
 |  Built-in immutable sequence.
 |
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |
 |  If the argument is a tuple, the return value is the same object.
 |
 |  Built-in subclasses:
 |      asyncgen_hooks
 |      UnraisableHookArgs
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __getnewargs__(self, /)
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __iter__(self, /)
 |      Implement iter(sel

Type:        tuple
String form: (2,)
Length:      1
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [16]:
np.ndarray.shape??

Type:        getset_descriptor
String form: <attribute 'shape' of 'numpy.ndarray' objects>
Docstring:  
Tuple of array dimensions.

The shape property is usually used to get the current shape of an array,
but may also be used to reshape the array in-place by assigning a tuple of
array dimensions to it.  As with `numpy.reshape`, one of the new shape
dimensions can be -1, in which case its value is inferred from the size of
the array and the remaining dimensions. Reshaping an array in-place will
fail if a copy is required.

.. warning::

    Setting ``arr.shape`` is discouraged and may be deprecated in the
    future.  Using `ndarray.reshape` is the preferred approach.

Examples
--------
>>> import numpy as np
>>> x = np.array([1, 2, 3, 4])
>>> x.shape
(4,)
>>> y = np.zeros((2, 3, 4))
>>> y.shape
(2, 3, 4)
>>> y.shape = (3, 8)
>>> y
array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])
>>> y.sha

In [18]:
np.shape??

Signature:       np.shape(a)
Call signature:  np.shape(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function shape at 0x000002396AF42520>
File:            c:\users\kaise\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Source:         
@array_function_dispatch(_shape_dispatcher)
def shape(a):
    """
    Return the shape of an array.

    Parameters
    ----------
    a : array_like
        Input array.

    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.

    See Also
    --------
    len : ``len(a)`` is equivalent to ``np.shape(a)[0]`` for N-D arrays with
          ``N>=1``.
    ndarray.shape : Equivalent array method.

    Examples
    --------
    >>> import numpy as np
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 3]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()

    >>> a = np.array([(1, 2), (3, 4), (5,

In [19]:
np.ndim??


Signature:       np.ndim(a)
Call signature:  np.ndim(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function ndim at 0x000002396AF43880>
File:            c:\users\kaise\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Source:         
@array_function_dispatch(_ndim_dispatcher)
def ndim(a):
    """
    Return the number of dimensions of an array.

    Parameters
    ----------
    a : array_like
        Input array.  If it is not already an ndarray, a conversion is
        attempted.

    Returns
    -------
    number_of_dimensions : int
        The number of dimensions in `a`.  Scalars are zero-dimensional.

    See Also
    --------
    ndarray.ndim : equivalent method
    shape : dimensions of array
    ndarray.shape : dimensions of array

    Examples
    --------
    >>> import numpy as np
    >>> np.ndim([[1,2,3],[4,5,6]])
    2
    >>> np.ndim(np.array([[1,2,3],[4,5,6]]))
    2
    >>> np.ndim(1)
    0

    """
    try:
        return a.ndim
 

In [22]:
np.size??

Signature:       np.size(a, axis=None)
Call signature:  np.size(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function size at 0x000002396AF439C0>
File:            c:\users\kaise\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Source:         
@array_function_dispatch(_size_dispatcher)
def size(a, axis=None):
    """
    Return the number of elements along a given axis.

    Parameters
    ----------
    a : array_like
        Input data.
    axis : int, optional
        Axis along which the elements are counted.  By default, give
        the total number of elements.

    Returns
    -------
    element_count : int
        Number of elements along the specified axis.

    See Also
    --------
    shape : dimensions of array
    ndarray.shape : dimensions of array
    ndarray.size : number of elements in array

    Examples
    --------
    >>> import numpy as np
    >>> a = np.array([[1,2,3],[4,5,6]])
    >>> np.size(a)
    6
    >>> np.size(a,1)

In [24]:
help(np.ndarray.dtype)

Help on getset descriptor numpy.ndarray.dtype:

dtype
    Data-type of the array's elements.

    .. warning::

        Setting ``arr.dtype`` is discouraged and may be deprecated in the
        future.  Setting will replace the ``dtype`` without modifying the
        memory (see also `ndarray.view` and `ndarray.astype`).

    Parameters
    ----------
    None

    Returns
    -------
    d : numpy dtype object

    See Also
    --------
    ndarray.astype : Cast the values contained in the array to a new data-type.
    ndarray.view : Create a view of the same data but a different data-type.
    numpy.dtype

    Examples
    --------
    >>> import numpy as np
    >>> x = np.arange(4).reshape((2, 2))
    >>> x
    array([[0, 1],
           [2, 3]])
    >>> x.dtype
    dtype('int64')   # may vary (OS, bitness)
    >>> isinstance(x.dtype, np.dtype)
    True



In [ ]:
np.ndarray.reshape??

np.reshape??


Signature:       np.reshape(a, /, shape=None, order='C', *, newshape=None, copy=None)
Call signature:  np.reshape(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function reshape at 0x000002396AF40C20>
File:            c:\users\kaise\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Source:         
@array_function_dispatch(_reshape_dispatcher)
def reshape(a, /, shape=None, order='C', *, newshape=None, copy=None):
    """
    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    shape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of ``a`` using this i

In [3]:
import numpy as np
np.ndarray.flatten??

Docstring:
a.flatten(order='C')

Return a copy of the array collapsed into one dimension.

Parameters
----------
order : {'C', 'F', 'A', 'K'}, optional
    'C' means to flatten in row-major (C-style) order.
    'F' means to flatten in column-major (Fortran-
    style) order. 'A' means to flatten in column-major
    order if `a` is Fortran *contiguous* in memory,
    row-major order otherwise. 'K' means to flatten
    `a` in the order the elements occur in memory.
    The default is 'C'.

Returns
-------
y : ndarray
    A copy of the input array, flattened to one dimension.

See Also
--------
ravel : Return a flattened array.
flat : A 1-D flat iterator over the array.

Examples
--------
>>> import numpy as np
>>> a = np.array([[1,2], [3,4]])
>>> a.flatten()
array([1, 2, 3, 4])
>>> a.flatten('F')
array([1, 3, 2, 4])
Type:      method_descriptor

In [5]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [6]:
np.sort??

Signature:       np.sort(a, axis=-1, kind=None, order=None, *, stable=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x00000187893FB880>
File:            c:\users\kaise\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Source:         
@array_function_dispatch(_sort_dispatcher)
def sort(a, axis=-1, kind=None, order=None, *, stable=None):
    """
    Return a sorted copy of an array.

    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and,
        in general, the actual implementation will vary w

In [7]:
np.concatenate??

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...),
    axis=0,
    out=None,
    dtype=None,
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'