In [3]:
import numpy as  np

a = np.array([1,2,3])

print(a)

[1 2 3]


In [7]:
import numpy as np

a = np.array([[1.,2.,1.],
             [2.,3.,1.]])

print(a)


a.shape

[[1. 2. 1.]
 [2. 3. 1.]]


(2, 3)

In [9]:
import numpy as np

a = np.array(
    [1,2,3],
    dtype= np.float32
)


print(a.dtype)

a.itemsize

float32


4

In [ ]:
data = np.array([[1.5, -0.1, 3],
                 [0, -3, 6.5]])

data * 10

data + data

data.shape

data.dtype

b  = np.array([
    [1,2],
    [3,4]
])

print(b)

b.shape

b.dtype



[[1 2]
 [3 4]]


dtype('int64')

In [19]:
a = [1,2,3]

a * 10

[1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3]

In [ ]:
np.array([1, 2, 3])



array([1, 2, 3])

In [ ]:
# 1. Creating Arrays with np.array()

import numpy as np


data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

print(arr1)

arr1.dtype

arr1.size

arr1.ndim

arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])


arr2

arr2.dtype

arr2.size

arr2.ndim

arr2.shape

np.zeros(9)

# np.zeros Creates arrays filled with zeros.

np.zeros((1,2))

np.zeros((5,7))

np.ones((2,3))

np.empty((1,2,2))

"""
np.empty faster than np.zeros  foro overwriting with zero 
"""

np.empty((2, 3, 2))

np.arange(16) 

"""
np.arange  is like range  
"""

np.arange(0,10, 2)


""" 
np.arange(start, stop, step)
"""








[6.  7.5 8.  0.  1. ]


array([0, 2, 4, 6, 8])

In [1]:
import numpy as np

# Creating NumPy arrays with explicit data types (dtype)

arr = np.array(
    [1, 2, 3],
    dtype=np.int32
)

print(arr)
print(arr.dtype)


arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)


# Original integer array
c = np.array([1, 2, 3, 4, 5])

# Convert integer array to float64 using astype()
float_c = c.astype(np.float64)

print(float_c)
print(float_c.dtype)


"""
NumPy dtype Notes
-----------------

dtype
-----
dtype stands for "data type".

It defines:
- how NumPy stores values in memory
- memory size of each element
- type of operations performed

Examples:
- np.int32   -> 32-bit integer
- np.float64 -> 64-bit floating point number


astype()
--------
Syntax:
    array.astype(new_dtype)

Purpose:
- Converts an array from one datatype to another.

Important:
- astype() creates and returns a NEW array.
- Original array remains unchanged.


Example:
--------
a = np.array([1, 2, 3])

b = a.astype(np.float64)

Result:
- a.dtype -> int64/int32
- b.dtype -> float64


Type Conversion Behavior
------------------------
NumPy does NOT round values during integer conversion.

It truncates toward zero.

Example:
--------
x = np.array([1.9, -2.7, 3.5])

x.astype(np.int32)

Output:
array([ 1, -2,  3], dtype=int32)
"""

[1 2 3]
int32
float64
int32
[1. 2. 3. 4. 5.]
float64


'\nNumPy dtype Notes\n-----------------\n\ndtype\n-----\ndtype stands for "data type".\n\nIt defines:\n- how NumPy stores values in memory\n- memory size of each element\n- type of operations performed\n\nExamples:\n- np.int32   -> 32-bit integer\n- np.float64 -> 64-bit floating point number\n\n\nastype()\n--------\nSyntax:\n    array.astype(new_dtype)\n\nPurpose:\n- Converts an array from one datatype to another.\n\nImportant:\n- astype() creates and returns a NEW array.\n- Original array remains unchanged.\n\n\nExample:\n--------\na = np.array([1, 2, 3])\n\nb = a.astype(np.float64)\n\nResult:\n- a.dtype -> int64/int32\n- b.dtype -> float64\n\n\nType Conversion Behavior\n------------------------\nNumPy does NOT round values during integer conversion.\n\nIt truncates toward zero.\n\nExample:\n--------\nx = np.array([1.9, -2.7, 3.5])\n\nx.astype(np.int32)\n\nOutput:\narray([ 1, -2,  3], dtype=int32)\n'

In [1]:
import numpy as np

x = np.array([1,2,3])

print(x)

[1 2 3]


In [ ]:
np.array([-1, 2, 3],
         dtype=np.int8
         
         )

"""
int8 is signed integer data type 

both positive and negative numbers
"""

array([-1,  2,  3], dtype=int8)

In [3]:
np.array(
    [0, 1, 255],
    dtype=np.uint8

)

array([  0,   1, 255], dtype=uint8)

In [ ]:
a = np.array(
    [1.5, 2.7],
    dtype = np.float32
    )


a



"""
less precision for float32 
"""


array([1.5, 2.7], dtype=float32)

In [7]:
a = np.array(
    [1.5, 2.7],
    dtype=np.float64

)


a

array([1.5, 2.7])

In [8]:
b = np.array(
    [True, False, True],
    dtype=bool
)

print(b)

[ True False  True]


In [10]:
s = np.array(
    ["cat", "dog"],
    dtype='S10'
)

print(s)

[b'cat' b'dog']


In [11]:
arr = np.array(
    [1, 2, 3],
    dtype=np.int32


)

print(arr)

[1 2 3]


In [ ]:
a = np.array(
    ["1", "2", "hello"]
)

a.astype(np.float64)



``

ValueError: could not convert string to float: np.str_('hello')

In [ ]:
import numpy as np

int_array = np.arange(10)

# print(int_array)

int_array

calibers = np.array(
    [.22, .270, .357, .380, .44, .50],
    dtype=np.float64
)


calibers

converted = int_array.astype(calibers.dtype)


int_array

converted

converted.dtype

dtype('float64')

In [ ]:
"""" as type always createas a copy
"""



In [35]:
"""
========================================================
Arithmetic with NumPy Arrays
========================================================

One of the biggest advantages of NumPy is:

    Vectorization

Vectorization means:
    Performing operations on entire arrays at once
    without writing explicit Python loops.

Advantages:
    • Faster
    • Cleaner syntax
    • Memory efficient
"""

import numpy as np


# ======================================================
# Creating a 2D NumPy Array
# ======================================================

arr = np.array(
    [
        [1.0, 2.0, 3.0],
        [4.0, 5.0, 6.0]
    ]
)

print("Array:\n", arr)

print("\nShape of array:")
print(arr.shape)


# ======================================================
# Element-wise Arithmetic Operations
# ======================================================

# Multiplication (element by element)
print("\nElement-wise multiplication:")
print(arr * arr)

# Subtraction
# Every element subtracts itself
print("\nElement-wise subtraction:")
print(arr - arr)


# ======================================================
# Scalar Operations
# ======================================================

"""
Scalar:
    A single number.

NumPy automatically applies the scalar
to every element in the array.

This mechanism is called:
    Broadcasting
"""

print("\nScalar division:")
print(1 / arr)

print("\nPower operation:")
print(arr ** 2)


# ::contentReference[oaicite:0]{index=0}



# ======================================================
# Comparison Operations
# ======================================================

arr2 = np.array(
    [
        [0.0, 4.0, 1.0],
        [7.0, 2.0, 12.0]
    ]
)

print("\nSecond array:\n", arr2)

# Element-wise comparison
print("\nComparison (arr2 > arr):")
print(arr2 > arr)


# ======================================================
# Boolean Indexing / Filtering
# ======================================================

"""
Boolean arrays are heavily used for:
    • Filtering
    • Masking
    • Conditions
"""

print("\nElements greater than 3:")
print(arr[arr > 3])


# ======================================================
# Matrix Multiplication
# ======================================================

"""
Element-wise multiplication:
    arr * arr

Matrix multiplication:
    arr @ arr.T
"""

print("\nMatrix multiplication using @ operator:")
print(arr @ arr.T)

print("\nMatrix multiplication using np.dot():")
print(np.dot(arr, arr.T))


# ======================================================
# Broadcasting Examples
# ======================================================

# Scalar broadcasting
print("\nBroadcasting with scalar:")
print(arr + 10)

# Array broadcasting
print("\nBroadcasting with 1D array:")
print(arr + np.array([1, 2, 3]))


# ======================================================
# Mental Model
# ======================================================

"""
Think of NumPy arithmetic as:

    Parallel operations on entire blocks of memory

instead of:
    • Python loops
    • One element at a time

This is why NumPy is extremely fast.
"""

Array:
 [[1. 2. 3.]
 [4. 5. 6.]]

Shape of array:
(2, 3)

Element-wise multiplication:
[[ 1.  4.  9.]
 [16. 25. 36.]]

Element-wise subtraction:
[[0. 0. 0.]
 [0. 0. 0.]]

Scalar division:
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

Power operation:
[[ 1.  4.  9.]
 [16. 25. 36.]]

Second array:
 [[ 0.  4.  1.]
 [ 7.  2. 12.]]

Comparison (arr2 > arr):
[[False  True False]
 [ True False  True]]

Elements greater than 3:
[4. 5. 6.]

Matrix multiplication using @ operator:
[[14. 32.]
 [32. 77.]]

Matrix multiplication using np.dot():
[[14. 32.]
 [32. 77.]]

Broadcasting with scalar:
[[11. 12. 13.]
 [14. 15. 16.]]

Broadcasting with 1D array:
[[2. 4. 6.]
 [5. 7. 9.]]


'\nThink of NumPy arithmetic as:\n\n    Parallel operations on entire blocks of memory\n\ninstead of:\n    • Python loops\n    • One element at a time\n\nThis is why NumPy is extremely fast.\n'

In [77]:
"""
========================================================
NumPy Indexing and Slicing
========================================================

Topics Covered:
    • 1D indexing
    • Slicing
    • Slice views vs copies
    • 2D indexing
    • 3D indexing
    • Row/column slicing
    • Broadcasting during assignment

Important Concept:
    NumPy slices are usually VIEWS, not copies.

This means:
    Modifying a slice can also modify
    the original array.
"""

import numpy as np


# ======================================================
# 1D ARRAY INDEXING
# ======================================================

# Create array from 0 to 9
arr = np.arange(10)

print("Original Array:")
print(arr)


# ------------------------------------------------------
# Accessing single element
# ------------------------------------------------------

print("\nElement at index 5:")
print(arr[5])


# ------------------------------------------------------
# Basic slicing
# ------------------------------------------------------

print("\nElements from index 5 to 7:")
print(arr[5:8])


# ------------------------------------------------------
# Assigning scalar value to slice
# ------------------------------------------------------

"""
Broadcasting occurs automatically.

The scalar value 12 is propagated
to every element in the slice.
"""

arr[5:8] = 12

print("\nAfter arr[5:8] = 12")
print(arr)


# ======================================================
# SLICES ARE VIEWS
# ======================================================

"""
arr_slice does NOT create a copy.

It creates a VIEW into the original array.
"""

arr_slice = arr[5:8]

print("\nSlice View:")
print(arr_slice)


# ------------------------------------------------------
# Modifying slice affects original array
# ------------------------------------------------------

arr_slice[1] = 12345

print("\nModified Slice:")
print(arr_slice)

print("\nOriginal Array After Slice Modification:")
print(arr)


# ------------------------------------------------------
# [:] selects entire slice
# ------------------------------------------------------

arr_slice[:] = 64

print("\nAfter arr_slice[:] = 64")
print(arr_slice)

print("\nOriginal Array:")
print(arr)


# ======================================================
# CREATING AN INDEPENDENT COPY
# ======================================================

"""
Use .copy() when you want an
independent array.
"""

copied_slice = arr[5:8].copy()

copied_slice[0] = 999

print("\nCopied Slice:")
print(copied_slice)

print("\nOriginal Array Remains Unchanged:")
print(arr)


# ======================================================
# 2D ARRAY INDEXING
# ======================================================

arr2d = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

print("\n2D Array:")
print(arr2d)


# ------------------------------------------------------
# Accessing rows
# ------------------------------------------------------

print("\nThird Row:")
print(arr2d[2])


# ------------------------------------------------------
# Accessing individual elements
# ------------------------------------------------------

print("\nUsing Recursive Indexing:")
print(arr2d[0][2])

print("\nUsing Comma-Separated Indexing:")
print(arr2d[0, 2])


# ======================================================
# 3D ARRAY INDEXING
# ======================================================

arr3d = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ]
    ]
)

print("\n3D Array:")
print(arr3d)


# ------------------------------------------------------
# Copying subarray
# ------------------------------------------------------

old_values = arr3d[0].copy()

print("\nCopied First Block:")
print(old_values)


# ------------------------------------------------------
# Assign scalar to subarray
# ------------------------------------------------------

"""
Scalar broadcasting occurs here.

Every element in arr3d[0]
becomes 42.
"""

arr3d[0] = 42

print("\nAfter arr3d[0] = 42")
print(arr3d)


# ------------------------------------------------------
# Restore original values
# ------------------------------------------------------

arr3d[0] = old_values

print("\nRestored Original Values:")
print(arr3d)


# ------------------------------------------------------
# Selecting deeper dimensions
# ------------------------------------------------------

x = arr3d[1]

print("\nSecond Block:")
print(x)

print("\nFirst Row of Second Block:")
print(x[0])


# ======================================================
# 2D ARRAY SLICING
# ======================================================

print("\nOriginal arr2d:")
print(arr2d)


# ------------------------------------------------------
# First two rows
# ------------------------------------------------------

print("\nFirst Two Rows:")
print(arr2d[:2])


# ------------------------------------------------------
# Row and column slicing
# ------------------------------------------------------

"""
arr2d[:2, 1:]

Meaning:
    • First 2 rows
    • Columns starting from index 1
"""

print("\nFirst Two Rows, Columns From Index 1:")
print(arr2d[:2, 1:])


# ======================================================
# MIXING INDEXES AND SLICES
# ======================================================

"""
Using:
    integer index + slice

reduces dimensions.
"""

lower_dim = arr2d[1, :2]

print("\nOriginal arr2d:")
print(arr2d)

print("\nLower Dimensional Slice:")
print(lower_dim)

print("\nShape of lower_dim:")
print(lower_dim.shape)


# ======================================================
# COLON (:)
# ======================================================

"""
Colon means:
    Select the entire axis
"""

print("\nAll Rows, First Column:")
print(arr2d[:, :1])


# ======================================================
# ASSIGNMENT TO SLICES
# ======================================================

"""
Assignment modifies the selected region.
"""

arr2d[:2, 1:] = 0

print("\nUpdated arr2d:")
print(arr2d)


# ======================================================
# FINAL NOTE
# ======================================================

"""
Mental Model:

NumPy indexing and slicing operate
directly on memory views.

Advantages:
    • Fast
    • Memory efficient
    • Avoids unnecessary copies

But:
    Modifying slices can affect
    the original array.
"""

Original Array:
[0 1 2 3 4 5 6 7 8 9]

Element at index 5:
5

Elements from index 5 to 7:
[5 6 7]

After arr[5:8] = 12
[ 0  1  2  3  4 12 12 12  8  9]

Slice View:
[12 12 12]

Modified Slice:
[   12 12345    12]

Original Array After Slice Modification:
[    0     1     2     3     4    12 12345    12     8     9]

After arr_slice[:] = 64
[64 64 64]

Original Array:
[ 0  1  2  3  4 64 64 64  8  9]

Copied Slice:
[999  64  64]

Original Array Remains Unchanged:
[ 0  1  2  3  4 64 64 64  8  9]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Third Row:
[7 8 9]

Using Recursive Indexing:
3

Using Comma-Separated Indexing:
3

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Copied First Block:
[[1 2 3]
 [4 5 6]]

After arr3d[0] = 42
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]

Restored Original Values:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Second Block:
[[ 7  8  9]
 [10 11 12]]

First Row of Second Block:
[7 8 9]

Original arr2d:
[[1 2 3]
 [4 5 6]
 [

'\nMental Model:\n\nNumPy indexing and slicing operate\ndirectly on memory views.\n\nAdvantages:\n    • Fast\n    • Memory efficient\n    • Avoids unnecessary copies\n\nBut:\n    Modifying slices can affect\n    the original array.\n'

In [94]:
"""
========================================================
NumPy Boolean Indexing
========================================================

Boolean indexing allows you to:

    • Filter data using conditions
    • Select specific rows/columns
    • Modify values conditionally

Core Idea:
    Comparisons on NumPy arrays are vectorized.

This means:
    Operations happen element-wise
    without explicit Python loops.
"""

import numpy as np


# ======================================================
# SAMPLE DATA
# ======================================================

names = np.array(
    ["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"]
)

data = np.array(
    [
        [4, 7],
        [0, 2],
        [-5, 6],
        [0, 0],
        [1, 2],
        [-12, -4],
        [3, 4]
    ]
)

print("Names Array:")
print(names)

print("\nData Array:")
print(data)


# ======================================================
# BOOLEAN COMPARISON
# ======================================================

"""
Comparison operations are vectorized.

Each element is compared individually.
"""

print("\nnames == 'Bob'")
print(names == "Bob")


# ======================================================
# BOOLEAN INDEXING
# ======================================================

"""
Boolean arrays can be used as indexes.

Only rows where condition is True
are selected.
"""

print("\nRows where name is 'Bob':")
print(data[names == "Bob"])


# ======================================================
# ROW + COLUMN SELECTION
# ======================================================

print("\nRows where name is 'Bob', columns from index 1:")
print(data[names == "Bob", 1:])

print("\nRows where name is 'Bob', only column index 1:")
print(data[names == "Bob", 1])


# ======================================================
# NEGATION
# ======================================================

"""
!= means:
    Not equal

~ means:
    Logical NOT / inversion
"""

print("\nNames not equal to 'Bob':")
print(names != "Bob")

print("\nNegating condition using ~:")
print(~(names == "Bob"))


print("\nRows where name is NOT 'Bob':")
print(data[~(names == "Bob")])


# ======================================================
# USING CONDITION VARIABLES
# ======================================================

cond = names == "Bob"

print("\nStored Boolean Condition:")
print(cond)

print("\nUsing condition variable:")
print(data[~cond])


# ======================================================
# MULTIPLE CONDITIONS
# ======================================================

"""
Use:
    &  -> AND
    |  -> OR

Do NOT use:
    and
    or

because Python keywords do not work
with NumPy Boolean arrays.
"""

mask = (names == "Bob") | (names == "Will")

print("\nCombined Boolean Mask:")
print(mask)

print("\nRows where name is Bob OR Will:")
print(data[mask])


# ======================================================
# IMPORTANT NOTE ABOUT COPIES
# ======================================================

"""
Boolean indexing creates COPIES,
not views.

Unlike slicing:
    data[mask]

returns a new independent array.
"""


# ======================================================
# MODIFYING VALUES WITH BOOLEAN INDEXING
# ======================================================

"""
Boolean indexing can also be used
for conditional assignment.
"""

print("\nOriginal Data:")
print(data)


# ------------------------------------------------------
# Replace negative values with 0
# ------------------------------------------------------

data[data < 0] = 0

print("\nAfter replacing negative values with 0:")
print(data)


# ======================================================
# MODIFYING ENTIRE ROWS
# ======================================================

"""
Rows where condition is True
can be updated completely.
"""

data[names != "Joe"] = 7

print("\nAfter setting rows not equal to 'Joe' to 7:")
print(data)


# ======================================================
# IMPORTANT CONCEPTS SUMMARY
# ======================================================

"""
Boolean Indexing Rules
----------------------

1. Comparisons are vectorized

    names == "Bob"

2. Boolean arrays must match axis length

3. Use:
       &
       |
       ~

   instead of:
       and
       or
       not

4. Boolean indexing returns COPIES

5. Boolean indexing is powerful for:
       • Filtering
       • Data cleaning
       • Conditional updates
       • Machine Learning preprocessing
"""

Names Array:
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Data Array:
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]

names == 'Bob'
[ True False False  True False False False]

Rows where name is 'Bob':
[[4 7]
 [0 0]]

Rows where name is 'Bob', columns from index 1:
[[7]
 [0]]

Rows where name is 'Bob', only column index 1:
[7 0]

Names not equal to 'Bob':
[False  True  True False  True  True  True]

Negating condition using ~:
[False  True  True False  True  True  True]

Rows where name is NOT 'Bob':
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]

Stored Boolean Condition:
[ True False False  True False False False]

Using condition variable:
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]

Combined Boolean Mask:
[ True False  True  True  True False False]

Rows where name is Bob OR Will:
[[ 4  7]
 [-5  6]
 [ 0  0]
 [ 1  2]]

Original Data:
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]

After replacing 

'\nBoolean Indexing Rules\n----------------------\n\n1. Comparisons are vectorized\n\n    names == "Bob"\n\n2. Boolean arrays must match axis length\n\n3. Use:\n       &\n       |\n       ~\n\n   instead of:\n       and\n       or\n       not\n\n4. Boolean indexing returns COPIES\n\n5. Boolean indexing is powerful for:\n       • Filtering\n       • Data cleaning\n       • Conditional updates\n       • Machine Learning preprocessing\n'

In [ ]:
arr = np.zeros((8, 4))

arr

for i in range(8):
    arr[i] = i

arr

arr[[4, 3, 0, 6]]  

 #select arbitrary rows


# return copy

arr[[-3, -5, -7]]







array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.arange(32).reshape((8, 4))

arr

print(arr)


result = arr[
    [1, 5, 7, 2],
    [0, 3, 1, 2]
]
# select individual elements

result

arr[1,0]
arr[5,3]

# rectangular selection

# 2 step indexing

rectangular = arr[
    [1, 5, 7, 2]
][:, [0,3,1,2]]

rectangular



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])